
server {
    # On ecoute sur le port standard 443 en ipv4 et ipv6
    listen 443 ssl;
    listen [::]:443 ssl;

    # Le nom de domaine imposee par le sujet
    server_name sm-gaidi.42.fr;

    # Les chemins vers notre certificat ssl et notre cle privee
    ssl_certificate /etc/nginx/ssl/inception.crt;
    ssl_certificate_key /etc/nginx/ssl/inception.key;

    # Restriction stricte des protocoles de securite.
    ssl_protocols TLSv1.2 TLSv1.3;

    # Le dossier racine ou NGINX ira chercher les fichiers web
    root /var/www/html;
    index index.php index.html index.htm;

    # Comportement par défaut : si le fichier n'existe pas, renvoyer une erreur 404
    location / {
        try_files $uri $uri/ =404;
    }

    # On traite tous les fichiers .php
    location ~ \.php$ {
        include snippets/fastcgi-php.conf;
        fastcgi_pass wordpress:9000;
    }
}