
# on cible la pool www.
[www]

# On demande a PHP-FPM de s'executer avec l'utilisateur et le groupe www-data
# afin de ne pas utiliser root et donc de limiter ses droits.
user = www-data
group = www-data

# On demande a PHP-FPM d'ecouter les requetes de fastCGI sur le port 9000 (Convention).
listen = 9000

# On demande a PHP-FPM de conserver les variables d'environnement.
clear_env = no